const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  loadNote: () => ipcRenderer.invoke('load-note'),
  saveNote: (content) => ipcRenderer.send('save-note', content),
  listScenes: () => ipcRenderer.invoke('list-scenes'),
  getScene: (sceneId) => ipcRenderer.invoke('get-scene', sceneId),
  createScene: (payloadJSON) => ipcRenderer.invoke('create-scene', payloadJSON),
  saveScene: (payloadJSON) => ipcRenderer.invoke('save-scene-v4', payloadJSON),
  renameScene: (payloadJSON) => ipcRenderer.invoke('rename-scene', payloadJSON),
  duplicateScene: (payloadJSON) => ipcRenderer.invoke('duplicate-scene', payloadJSON),
  deleteScene: (sceneId) => ipcRenderer.invoke('delete-scene', sceneId),
  loadSessionState: () => ipcRenderer.invoke('load-session-state'),
  saveSessionState: (stateJSON) => ipcRenderer.invoke('save-session-state', stateJSON),
  saveCharacter: (id, dataJSON) => ipcRenderer.send('save-character', id, dataJSON),
  deleteCharacter: (id) => ipcRenderer.send('delete-character', id),
  deleteFile: (filePath) => ipcRenderer.send('delete-file', filePath),
  getCharacters: () => ipcRenderer.invoke('get-characters'),
  getCompendiumEntries: () => ipcRenderer.invoke('get-compendium-entries'),
  saveCompendiumEntry: (entryJSON) => ipcRenderer.invoke('save-compendium-entry', entryJSON),
  deleteCompendiumEntry: (id) => ipcRenderer.invoke('delete-compendium-entry', id),
  importCharacterEquipmentCompendium: () => ipcRenderer.invoke('import-character-equipment-compendium'),
  getAssetsLibrary: () => ipcRenderer.invoke('get-assets-library'),
  importAsset: (payloadJSON) => ipcRenderer.invoke('import-asset', payloadJSON),
  saveAssetMetadata: (assetJSON) => ipcRenderer.invoke('save-asset-metadata', assetJSON),
  deleteAsset: (assetId) => ipcRenderer.invoke('delete-asset', assetId),
  renameAsset: (payloadJSON) => ipcRenderer.invoke('rename-asset', payloadJSON),
  scanAssetsFolders: () => ipcRenderer.invoke('scan-assets-folders'),
  validateAssetsLibrary: () => ipcRenderer.invoke('validate-assets-library')
});
